spring:
  rabbitmq:
    host: 192.168.1.132
    port: 5672
    password: admin
    username: admin
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://192.168.0.104:3306/SpringCloud_Sell?characterEncoding=utf-8&useSSL=false
env:
  dev
