spring:
  zipkin:
    base-url: http://192.168.1.132:9411/
  sleuth:
    sampler:
      percentage: 1
  rabbitmq:
    host: 192.168.1.132
    port: 5672
    password: admin
    username: admin
  redis:
    host: 192.168.1.133
    port: 6379
hystrix:
  command:
    default: #默认设置(全局)
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000
    getProductInfoList: #给某个方法设置超时
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000
management:
  context-path: /
env:
  dev
